### PR TITLE
Zaius Support

### PR DESCRIPTION
**Pull request by derekharmel**
Added support for [Zaius](http://zaius.com/) web event tracking.

### CODE REVIEW

**Comment by simpsora** [comment]
Going to merge now, and add the options page code in a subsequent PR (since this PR is off someone's fork).

**Comment by simpsora** [comment]
@MisterPhilip The options code is dynamic, so we shouldn't need to do anything further.  Thanks @derekharmel (and sorry for the delay)!

**Comment by MisterPhilip** [comment]
@simpsora - for Chrome it's dynamic, but Firefox isn't (https://github.com/simpsora/omnibug/blob/master/firefox/chrome/content/omnibug/options.xul). I believe that is the only place that'll need an update though.

**Comment by simpsora** [comment]
Good point @MisterPhilip -- you know my code better than I do! 😂 

Updated as part of https://github.com/simpsora/omnibug/pull/38; will see about doing a Firefox build.

**Comment by simpsora** [comment]
New [Chrome version](https://chrome.google.com/webstore/detail/omnibug/bknpehncffejahipecakbfkomebjmokl) published.

**Pull request merged**
